<?php
	// VALIDAÇÕES
	// filter_input -> filter_var

	/* Parâmetros de validação
	FILTER_SANITIZE_SPECIAL_CHARS
	FILTER_SANITIZE_NUMBER_INT
	FILTER_SANITIZE_NUMBER_FLOAT
	FILTER_SANITIZE_EMAIL

	FILTER_VALIDATE_INT
	FILTER_SANITIZE_FLOAT
	FILTER_SANITIZE_BOOLEAN
	FILTER_SANITIZE_EMAIL
	*/
